### ISSUE TITLE
Request: armeabi-v7a build

### ISSUE THREAD

**Issue by noto10** [edgan/SmartTubeManager#1]
Could we have a v7a version? Many devices are still limited to 32 bit. Thanks.

**Comment by edgan** [comment]
You say 32bit but also say arm64-v7a. I think you meant armeabi-v7a.

I have added smarttubemanager-1.0_armeabi-v7a.apk in releases. 

Tell me if it works for you.

Edit: I just realized I will need to update the app to make this actually usable for you. So I have more work to do. Hence I have removed the new apk.

**Comment by edgan** [comment]
Try smarttubemanager-1.0.1_armeabi-v7a.apk in releases.

**Comment by noto10** [comment]
> You say 32bit but also say arm64-v7a. I think you meant armeabi-v7a.
> 
> I have added smarttubemanager-1.0_armeabi-v7a.apk in releases.
> 
> Tell me if it works for you.
> 
> Edit: I just realized I will need to update the app to make this actually usable for you. So I have more work to do. Hence I have remoted the new apk.

Yes. Sorry for typo. Thanks for the provision. Testing it.

**Comment by edgan** [comment]
Any luck with the armeabi-v7a build?
